#!/usr/local/cpanel/3rdparty/bin/python3 -- or any python3
"""Generate cPanel UAPI OpenAPI spec files for the EAPodman module.

One ``Cpanel/API/EAPodman-<func>.openapi.yaml`` per UAPI function, matching the
cPanel package standard (OpenAPI 3.0.2, the standard UAPI response envelope,
BasicAuth, /execute server, CLI/URL/LiveAPI code samples). Validated by
``build-tools/openapi-lint`` (spectral + redocly). Re-run this to regenerate:

    python3 build-tools/gen-openapi.py

The generated ``EAPodman-<func>.openapi.yaml`` files are written flat into
``SOURCES/`` so the RPM/deb packaging can ship each as a ``SourceN`` (RPM
resolves ``%{SOURCEn}`` by basename, so shipped sources must not sit in a
subdirectory). See CPANEL-54037 / CPANEL-54143 and docs/uapi.md.
"""

import os
import yaml

HERE = os.path.dirname(os.path.abspath(__file__))
# Write the specs into the repo's SOURCES/ dir (this script lives in build-tools/).
OUT = os.path.join(os.path.dirname(HERE), "SOURCES")
MODULE = "EAPodman"
VERSION = "11.136.0.0"
TAG_CAT = "ea-podman Containers"

# --- the standard UAPI response envelope (result wrapper) -------------------
def envelope(data_schema):
    return {
        "type": "object",
        "properties": {
            "apiversion": {"description": "The version of the API.", "example": 3, "type": "integer"},
            "func": {"description": "The name of the method called.", "type": "string"},
            "module": {"description": "The name of the module called.", "example": MODULE, "type": "string"},
            "result": {
                "type": "object",
                "properties": {
                    "data": data_schema,
                    "errors": {
                        "description": "List of errors if the API failed.",
                        "example": None, "nullable": True, "type": "array",
                        "items": {"type": "string"},
                    },
                    "messages": {
                        "description": "List of messages generated by the API.",
                        "example": None, "nullable": True, "type": "array",
                        "items": {"type": "string"},
                    },
                    "metadata": {"type": "object", "properties": {}},
                    "status": {
                        "description": "* 1 - Success.\n* 0 - Failed. Check the `errors` field for more details.",
                        "enum": [0, 1], "example": 1, "type": "integer",
                    },
                    "warnings": {
                        "description": "List of warnings generated by the API.",
                        "example": None, "nullable": True, "type": "array",
                        "items": {"type": "string"},
                    },
                },
            },
        },
    }


# --- per-function data payload schemas --------------------------------------
CONTAINER_ENTRY = {
    "type": "object",
    "description": "A registered container, keyed by its generated name.",
    "properties": {
        "container_name": {"type": "string", "example": "myredis.bob.01"},
        "user": {"type": "string", "example": "bob"},
        "image": {"type": "string", "example": "docker.io/library/redis:alpine"},
        "pkg": {"type": "string", "nullable": True,
                "description": "The EA4 container-based package, or null for an arbitrary image.",
                "example": None},
        "ports": {"type": "array", "items": {"type": "string"},
                  "description": "host:container port mappings.", "example": ["10000:6379"]},
    },
}

DATA_LIST = {
    "type": "object",
    "description": "The caller's registered containers, keyed by container name.",
    "additionalProperties": CONTAINER_ENTRY,
    "example": {"myredis.bob.01": {
        "container_name": "myredis.bob.01", "user": "bob",
        "image": "docker.io/library/redis:alpine", "pkg": None,
        "ports": ["10000:6379"]}},
}
DATA_INSTALL = {
    "type": "object",
    "properties": {"container_name": {
        "description": "The generated name of the installed container.",
        "type": "string", "example": "myredis.bob.01"}},
}
DATA_NULL = {"default": None, "nullable": True, "type": "object"}
DATA_STATUS = {
    "type": "object",
    "description": "The container's systemd user-service state.",
    "properties": {
        "running": {"type": "integer", "enum": [0, 1],
                    "description": "1 if the service is active.", "example": 1},
        "enabled": {"type": "integer", "enum": [0, 1],
                    "description": "1 if the service is enabled.", "example": 1},
    },
    "example": {"running": 1, "enabled": 1},
}
DATA_CMD = {
    "type": "object",
    "description": "The exec'd command's captured output and exit status.",
    "properties": {
        "stdout": {"type": "string", "description": "Captured standard output.", "example": "Mon Jan  1 00:00:00 UTC 2026\n"},
        "stderr": {"type": "string", "description": "Captured standard error.", "example": ""},
        "exit_code": {"type": "integer", "description": "The command's own exit code (not the UAPI call's success/failure).", "example": 0},
        "stdout_truncated": {"type": "boolean", "description": "True if stdout was cut off at the output size cap.", "example": False},
        "stderr_truncated": {"type": "boolean", "description": "True if stderr was cut off at the output size cap.", "example": False},
    },
    "example": {"stdout": "Mon Jan  1 00:00:00 UTC 2026\n", "stderr": "", "exit_code": 0,
                "stdout_truncated": False, "stderr_truncated": False},
}

# --- parameter definitions --------------------------------------------------
P_NAME = {"name": "name", "in": "query", "required": True,
          "description": "An EA4 container-based package name, or an arbitrary container name.",
          "schema": {"type": "string", "example": "myredis"}}
P_IMAGE = {"name": "image", "in": "query", "required": False,
           "description": "The container image. Required for an arbitrary name; omit for an EA4 package (which supplies its own).",
           "schema": {"type": "string", "example": "docker.io/library/redis:alpine"}}
P_CONTAINER_PORT = {"name": "cpuser_port", "in": "query", "required": False,
                 "description": "A port inside the container to publish; repeatable (give cpuser_port more than once). The host port is assigned by the cPanel port authority.",
                 "schema": {"type": "array", "items": {"type": "integer", "example": 6379}}}
P_ENV = {"name": "env", "in": "query", "required": False,
         "description": "A KEY=VALUE environment pair; repeatable (give env more than once).",
         "schema": {"type": "array", "items": {"type": "string", "example": "TZ=UTC"}}}
P_RISK = {"name": "accept_arbitrary_image_risk", "in": "query", "required": False,
          "description": "Required to install an arbitrary (non-EA4-package) image, acknowledging the trust/reliability caveats.\n* `1` - Acknowledge and proceed.\n* `0` - Do not (default).",
          "schema": {"enum": [0, 1], "type": "integer", "example": 1}}
P_CONTAINER = {"name": "container_name", "in": "query", "required": True,
               "description": "The generated name of the container to act on.",
               "schema": {"type": "string", "example": "myredis.bob.01"}}
P_ARG = {"name": "arg", "in": "query", "required": True,
         "description": "The command and its arguments, in order; repeatable (give arg more than once). "
                         "At least one is required.",
         "schema": {"type": "array", "items": {"type": "string", "example": "date"}}}
P_CD = {"name": "cd", "in": "query", "required": False,
        "description": "An optional working directory inside the container. When given, the command runs from "
                        "that directory via the container's /bin/sh (cd DIR && exec ...); without it, no shell is used.",
        "schema": {"type": "string", "example": "/tmp"}}

FUNCS = {
    "list": {
        "summary": "List your ea-podman containers",
        "readonly": True,
        "description": "Return the caller's registered ea-podman containers, keyed by container name. Read-only.",
        "params": [], "data": DATA_LIST,
        "sample_args": [],
    },
    "install": {
        "summary": "Install and start an ea-podman container",
        "readonly": False,
        "description": "Install and start a rootless container for the caller. Synchronous, so installing an image that must be pulled can take a while.",
        "params": [P_NAME, P_IMAGE, P_CONTAINER_PORT, P_ENV, P_RISK], "data": DATA_INSTALL,
        "sample_args": [("name", "myredis"), ("image", "docker.io/library/redis:alpine"),
                        ("cpuser_port", "6379"), ("accept_arbitrary_image_risk", "1")],
    },
    "upgrade": {
        "summary": "Upgrade an ea-podman container",
        "readonly": False,
        "description": "Pull the latest image for the named container and recreate it. Synchronous, so it can take a while like install.",
        "params": [P_CONTAINER], "data": DATA_NULL,
        "sample_args": [("container_name", "myredis.bob.01")],
    },
    "uninstall": {
        "summary": "Uninstall an ea-podman container",
        "readonly": False,
        "description": "Stop, remove, and deregister the named container, and free its published ports.",
        "params": [P_CONTAINER], "data": DATA_NULL,
        "sample_args": [("container_name", "myredis.bob.01")],
    },
    "start": {
        "summary": "Start an ea-podman container",
        "readonly": False,
        "description": "Start the named container's systemd user service.",
        "params": [P_CONTAINER], "data": DATA_NULL,
        "sample_args": [("container_name", "myredis.bob.01")],
    },
    "stop": {
        "summary": "Stop an ea-podman container",
        "readonly": False,
        "description": "Stop the named container's systemd user service.",
        "params": [P_CONTAINER], "data": DATA_NULL,
        "sample_args": [("container_name", "myredis.bob.01")],
    },
    "restart": {
        "summary": "Restart an ea-podman container",
        "readonly": False,
        "description": "Restart the named container's systemd user service.",
        "params": [P_CONTAINER], "data": DATA_NULL,
        "sample_args": [("container_name", "myredis.bob.01")],
    },
    "status": {
        "summary": "Report an ea-podman container's state",
        "readonly": True,
        "description": "Report the named container's systemd user-service state (running/enabled). Read-only.",
        "params": [P_CONTAINER], "data": DATA_STATUS,
        "sample_args": [("container_name", "myredis.bob.01")],
    },
    "cmd": {
        "summary": "Run a one-shot command inside an ea-podman container",
        "readonly": False,
        "description": "Run a non-interactive command inside the named container (no TTY, no shell assumed) and "
                        "return its captured stdout, stderr, and exit code. An optional `cd` sets the working "
                        "directory. Works on hardened (hidepid=2) hosts and for jailshell / CageFS accounts.",
        "params": [P_CONTAINER, P_ARG, P_CD], "data": DATA_CMD,
        "sample_args": [("container_name", "myredis.bob.01"), ("arg", "date")],
    },
}


def cli_sample(func, args):
    lines = ["uapi --output=jsonpretty \\", "  --user=username \\", "  %s \\" % MODULE, "  %s" % func]
    if args:
        lines[-1] += " \\"
        for i, (k, v) in enumerate(args):
            tail = " \\" if i < len(args) - 1 else ""
            lines.append("  %s='%s'%s" % (k, v, tail))
    return "\n".join(lines) + "\n"


def url_sample(func, args):
    from urllib.parse import quote
    base = "https://hostname.example.com:2083/cpsess##########/execute/%s/%s" % (MODULE, func)
    if not args:
        return base
    qs = "&".join("%s=%s" % (k, quote(str(v), safe="")) for k, v in args)
    return base + "?" + qs


def liveapi_perl(func, args):
    if args:
        argblock = ",\n        {\n" + "".join(
            "            '%s' => '%s',\n" % (k, v) for k, v in args) + "        }"
    else:
        argblock = ""
    return (
        "use strict;\nuse Cpanel::LiveAPI ();\n\n"
        "my $cpanel = Cpanel::LiveAPI->new();\n\n"
        "print \"Content-type: text/plain\\r\\n\\r\\n\";\n\n"
        "my $response = $cpanel->uapi(\n        q/%s/,\n        q/%s/%s\n);\n\n"
        "if ($response->{cpanelresult}{result}{status}) {\n"
        "    print to_json($response->{cpanelresult}{result}{data});\n}\n"
        "else {\n    print to_json($response->{cpanelresult}{result}{errors});\n}\n\n"
        "$cpanel->end();\n\n"
        "sub to_json { require JSON; return JSON->new->pretty->encode($_[0]); }\n"
        % (MODULE, func, argblock)
    )


def liveapi_php(func, args):
    if args:
        argblock = ",\n        array (\n" + "".join(
            "            '%s' => '%s',\n" % (k, v) for k, v in args) + "        )"
    else:
        argblock = ""
    return (
        "<?php\n"
        "require_once \"/usr/local/cpanel/php/cpanel.php\";\n"
        "header('Content-Type: text/plain');\n"
        "$cpanel = new CPANEL();\n\n"
        "$response = $cpanel->uapi(\n        '%s',\n        '%s'%s\n);\n\n"
        "if ($response['cpanelresult']['result']['status']) {\n"
        "    print to_json($response['cpanelresult']['result']['data']);\n}\n"
        "else {\n    print to_json($response['cpanelresult']['result']['errors']);\n}\n\n"
        "$cpanel->end();\n\n"
        "function to_json($data) { return json_encode($data, JSON_PRETTY_PRINT); }\n"
        % (MODULE, func, argblock)
    )


def build(func, spec):
    args = spec["sample_args"]
    op = {
        "x-readonly": spec["readonly"],
        "description": spec["description"],
        "operationId": func,
        "parameters": spec["params"],
        "responses": {"200": {
            "description": "HTTP Request was successful.",
            "content": {"application/json": {"schema": envelope(spec["data"])}},
        }},
        "summary": spec["summary"],
        "tags": [MODULE, TAG_CAT],
        "x-codeSamples": [
            {"label": "CLI", "lang": "Shell", "source": cli_sample(func, args)},
            {"label": "URL", "lang": "HTTP", "source": url_sample(func, args)},
            {"label": "LiveAPI Perl", "lang": "Perl", "source": liveapi_perl(func, args)},
            {"label": "LiveAPI PHP", "lang": "PHP", "source": liveapi_php(func, args)},
        ],
        "x-cpanel-api-version": "UAPI",
        "x-cpanel-available-version": "ea-podman 1.0",
    }
    return {
        "openapi": "3.0.2",
        "info": {
            "title": "cPanel UAPI",
            "description": "UAPI accesses the cPanel interface's features. Use this API to access and modify cPanel account data and settings.",
            "version": VERSION,
            "contact": {"email": "cs@cpanel.net", "name": "WebPros International, LLC", "url": "https://cpanel.net/support/"},
            "license": {"name": "cPanel License", "url": "https://cpanel.net/legal-notices/"},
            "termsOfService": "https://cpanel.net/legal-notices/",
        },
        "externalDocs": {"url": "https://cpanel.net/developers/"},
        "components": {"schemas": {}, "securitySchemes": {"BasicAuth": {"scheme": "basic", "type": "http"}}},
        "security": [{"BasicAuth": []}],
        "servers": [{
            "description": "A server running cPanel.",
            "url": "https://{host}:{port}/execute",
            "variables": {
                "host": {"default": "cpanel-server.tld", "description": "The hostname of a server running cPanel"},
                "port": {"default": "2083", "description": "The cPanel port."},
            },
        }],
        "paths": {"/%s/%s" % (MODULE, func): {"get": op}},
        "tags": [
            {"description": "The %s module for UAPI." % MODULE, "name": MODULE},
            {"description": "Optional Applications / %s" % TAG_CAT, "name": TAG_CAT},
        ],
        "x-tagGroups": [{"name": "Optional Applications", "tags": [TAG_CAT]}],
    }


def main():
    for func, spec in FUNCS.items():
        doc = build(func, spec)
        path = os.path.join(OUT, "%s-%s.openapi.yaml" % (MODULE, func))
        with open(path, "w") as fh:
            fh.write("---\n")
            yaml.safe_dump(doc, fh, sort_keys=True, default_flow_style=False, width=100, allow_unicode=True)
        print("wrote", os.path.basename(path))


if __name__ == "__main__":
    main()
