mode=full
allowed_parents=/opt/cpanel/ea-podman/bin/ea-podman,/usr/local/cpanel/scripts/ea-podman,/usr/local/cpanel/whostmgr/bin/xml-api,/usr/local/cpanel/bin/removeacct,/usr/local/cpanel/bin/pkgacct,/usr/local/cpanel/uapi,/usr/local/cpanel/bin/process_user_tasks,/usr/local/cpanel/libexec/queueprocd
