#!/bin/bash

set -x

chmod 0700 /opt/cpanel/ea-podman/bin/compile.sh
/opt/cpanel/ea-podman/bin/compile.sh

if [ -f "/usr/local/cpanel/scripts/ea-podman" ]; then
    echo ""
else
    ln -s /opt/cpanel/ea-podman/bin/ea-podman /usr/local/cpanel/scripts/ea-podman
fi

if [ -f "/usr/bin/apt" ]; then
    chmod 0700 /usr/local/cpanel/bin/admin/Cpanel/ea_podman
    chmod 0600 /opt/cpanel/ea-podman/registered-containers.json
fi

if [ -e "/root/.ea-podman-tmp/registered-containers.json" ]; then
    # This is an upgrade, we copied the file to tmp, so copy it back
    mv /root/.ea-podman-tmp/registered-containers.json /opt/cpanel/ea-podman/registered-containers.json
    chmod 0600 /opt/cpanel/ea-podman/registered-containers.json
    rm -rf /root/.ea-podman-tmp
fi

# Always install the hooks, they are always removed on pre
/usr/local/cpanel/bin/manage_hooks prune; /bin/true;
/usr/local/cpanel/bin/manage_hooks add module PodmanHooks

set +x
echo "!!!! ATTENTION !!"
echo "!!!! If /proc is public it could lead to information disclosure. !!"
echo "Setting /proc to hidepid level 2 is recommended if possible."
echo "As root, run \`ea-podman subids\` and look for more information at the top of the output (if there is no output you are already covered)."
echo "!!!! /ATTENTION !!"
set -x

# On Rocky 9 and ONLY Rocky 9, there is a need for use to change the permissions on these
# programs

. /etc/os-release

if [ "$NAME" = "Rocky Linux" ]; then
    VAL=`echo $VERSION | sed -n '/^9\./p'`
    if [ "$VAL" != "" ]; then
		chmod 4755 /usr/bin/newgidmap
		chmod 4755 /usr/bin/newuidmap
    fi
fi

