#!/bin/bash

set -x

# Package removal, not upgrade
if [[ "$1" == "0" || "$1" == "remove" ]]; then
    if [ -x "/opt/cpanel/ea-podman/bin/ea-podman" ]; then
        /opt/cpanel/ea-podman/bin/ea-podman remove_containers --all

        if [ -x "/usr/bin/apt" ]; then
            rm -f /opt/cpanel/ea-podman/bin/ea-podman
        fi
    fi
else
    if [ -e "/opt/cpanel/ea-podman/registered-containers.json" ]; then
        # This is an upgrade, we need to preserve /opt/cpanel/ea-podman/registered-containers.json
        cp -f /opt/cpanel/ea-podman/registered-containers.json /tmp
    fi
fi

