#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - t/SOURCES-util-container-unit.t         Copyright 2026 WebPros International, LLC
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

use strict;
use warnings;

use Test::More;
use FindBin;
use File::Temp;
use Path::Tiny ();

our $HOMEDIR;

BEGIN {
    *CORE::GLOBAL::getpwuid = sub {
        my ($uid) = @_;
        return ( "bob", "x", $uid, $uid, "", "", "", $main::HOMEDIR, "/bin/bash" );
    };
}

require "$FindBin::Bin/../SOURCES/util.pm";

# Verbatim `podman generate systemd --restart-policy on-failure --name …`
# output from podman 5.8.2, line continuations and all.
my $PODMAN_UNIT = <<'END_UNIT';
# container-myapp.bob.01.service
# autogenerated by Podman 5.8.2
# Mon Aug 17 19:05:45 UTC 2026

[Unit]
Description=Podman container-myapp.bob.01.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=/run/user/1666/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStart=/usr/bin/podman start myapp.bob.01
ExecStop=/usr/bin/podman stop  \
	-t 10 myapp.bob.01
ExecStopPost=/usr/bin/podman stop  \
	-t 10 myapp.bob.01
PIDFile=/run/user/1666/containers/overlay-containers/407b3f/userdata/conmon.pid
Type=forking

[Install]
WantedBy=default.target
END_UNIT

# section => [ "Name=value", … ], continuation lines folded into the directive
# they continue, so a mangled continuation shows up as a changed directive.
sub parse_unit {
    my ($unit) = @_;

    my %section;
    my $current = "";
    for my $line ( split( m/\n/, $unit ) ) {
        next if $line =~ m/^\s*(?:#.*)?$/;

        if ( $line =~ m/^\s*\[(\w+)\]\s*$/ ) {
            $current = $1;
            $section{$current} ||= [];
            next;
        }

        if ( @{ $section{$current} || [] } && $section{$current}[-1] =~ s/\s*\\$// ) {
            $line =~ s/^\s+//;
            $section{$current}[-1] .= " $line";
            next;
        }

        push @{ $section{$current} }, $line;
    }

    return \%section;
}

subtest 'the directives land in the section they belong to' => sub {
    my $got = parse_unit( ea_podman::util::_add_container_unit_directives($PODMAN_UNIT) );

    for my $section ( sort keys %ea_podman::util::container_unit_directives ) {
        for my $directive ( @{ $ea_podman::util::container_unit_directives{$section} } ) {
            ok( ( grep { $_ eq $directive } @{ $got->{$section} } ), "[$section] has $directive" );

            my ($other) = grep { $_ ne $section } keys %ea_podman::util::container_unit_directives;
            ok( !( grep { $_ eq $directive } @{ $got->{$other} } ), "[$other] does not have $directive" );
        }
    }

    # The values the case's acceptance criteria name, spelled out here so a
    # change to any of them has to be a deliberate one.
    is_deeply(
        \%ea_podman::util::container_unit_directives,
        {
            Unit    => [ "StartLimitIntervalSec=300", "StartLimitBurst=3" ],
            Service => [ "RestartSec=5",              "SuccessExitStatus=143" ],
        },
        "the directive set is the one the container units are meant to get"
    );
};

subtest "podman's own directives are left exactly as they were" => sub {
    my $before = parse_unit($PODMAN_UNIT);
    my $after  = parse_unit( ea_podman::util::_add_container_unit_directives($PODMAN_UNIT) );

    is_deeply( [ sort keys %$after ], [ sort keys %$before ], "no section added or dropped" );

    for my $section ( sort keys %$before ) {
        my %added = map { $_ => 1 } @{ $ea_podman::util::container_unit_directives{$section} || [] };
        is_deeply(
            [ grep { !$added{$_} } @{ $after->{$section} } ],
            $before->{$section},
            "[$section] keeps its directives, in order"
        );
    }
};

subtest 'adding the directives twice adds them once' => sub {
    my $once  = ea_podman::util::_add_container_unit_directives($PODMAN_UNIT);
    my $twice = ea_podman::util::_add_container_unit_directives($once);

    is( $twice, $once, "a unit that already has them is unchanged" );
};

subtest 'a directive the generator already wrote wins' => sub {
    my $unit = $PODMAN_UNIT;
    $unit =~ s/^Restart=on-failure$/Restart=on-failure\nRestartSec=30/m;

    my $got = parse_unit( ea_podman::util::_add_container_unit_directives($unit) );

    is_deeply(
        [ grep { m/^RestartSec=/ } @{ $got->{Service} } ],
        ["RestartSec=30"],
        "RestartSec is not set twice"
    );
    ok( ( grep { $_ eq "SuccessExitStatus=143" } @{ $got->{Service} } ), "the other Service directive is still added" );
};

subtest 'a section the generator did not write is added' => sub {
    my $unit = "[Install]\nWantedBy=default.target\n";
    my $got  = parse_unit( ea_podman::util::_add_container_unit_directives($unit) );

    is_deeply( $got->{Unit},    [ "StartLimitIntervalSec=300", "StartLimitBurst=3" ],     "[Unit] was added" );
    is_deeply( $got->{Service}, [ "RestartSec=5",              "SuccessExitStatus=143" ], "[Service] was added" );
};

subtest 'generate_container_service writes the augmented unit and enables it' => sub {
    my $tmp = File::Temp->newdir();
    local $HOMEDIR = "$tmp";

    my @sysctl_calls;
    no warnings 'once';
    local *ea_podman::util::_podman_generate_systemd = sub { return $PODMAN_UNIT };
    local *ea_podman::util::sysctl                   = sub { push @sysctl_calls, [@_]; return 1 };

    ok( ea_podman::util::generate_container_service("myapp.bob.01"), "it reports success" );

    my $written = Path::Tiny::path("$tmp/.config/systemd/user/container-myapp.bob.01.service")->slurp;
    is( $written, ea_podman::util::_add_container_unit_directives($PODMAN_UNIT), "the unit on disk has the directives" );

    is_deeply(
        \@sysctl_calls,
        [ ["daemon-reload"], [ enable => "container-myapp.bob.01.service" ] ],
        "the manager is reloaded before the unit is enabled, so an existing container picks the change up"
    );
};

subtest 'a failed daemon-reload is not silent' => sub {
    my $tmp = File::Temp->newdir();
    local $HOMEDIR = "$tmp";

    no warnings 'once';
    local *ea_podman::util::_podman_generate_systemd = sub { return $PODMAN_UNIT };
    local *ea_podman::util::sysctl                   = sub { return $_[0] eq "daemon-reload" ? 0 : 1 };

    my @warnings;
    local $SIG{__WARN__} = sub { push @warnings, $_[0] };

    ok( ea_podman::util::generate_container_service("myapp.bob.01"), "it still enables the unit" );
    is( scalar @warnings, 1, "one warning" );
    like( $warnings[0], qr/reload/, "it says the reload failed, so a stale unit is not passed off as the new one" );
};

subtest 'reset_container_unit_failure' => sub {
    my @cmds;
    no warnings 'once';
    local *ea_podman::util::_systemctl_quiet = sub { push @cmds, [@_]; return 1 };

    ok( ea_podman::util::reset_container_unit_failure("myapp.bob.01"), "it reports success" );
    is_deeply( \@cmds, [ [ "reset-failed", "container-myapp.bob.01.service" ] ], "it resets that unit only" );

    like( ( eval { ea_podman::util::reset_container_unit_failure("../../etc/passwd") } || $@ ), qr/Invalid container name/, "the name is validated" );
};

done_testing();
